# This rule is not used by the project tmp itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ingress.example.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tmp
    app.kubernetes.io/managed-by: kustomize
  name: appingress-admin-role
rules:
- apiGroups:
  - ingress.example.com
  resources:
  - appingresses
  verbs:
  - '*'
- apiGroups:
  - ingress.example.com
  resources:
  - appingresses/status
  verbs:
  - get
